<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr">
	<head>
<?php include "_head.phi"; ?>
		<title>ARIA Decision Policy</title>
	</head>
	<body>
<?php include "_header.phi"; ?>
		<h1>ARIA Decision Policy</h1>

		<p>This document explains the decision process of the Accessible Rich Internet Applications Working Group.</p>
		<p>There are often divergent opinions on issues. It is important that all views are expressed and considered, but it is critical to Working Group function that it can come to conclusions. The procedures set out here describe how the WG discusses a topic and forms a decision, preferably by <a href="https://www.w3.org/Consortium/Process/#Consensus">consensus</a>. These procedures are designed to ensure that input is considered, whether in teleconferences or using asynchronous communication tools.</p>
		<p>The procedure to reach a decision is:</p>
		<ol>
			<li>Discussion on a topic proceeds until the chair believes that all expressed points of view have been heard and considered.</li>
			<li>When the chair believes that the group is ready to come to a decision, they announce a Call for Consensus (CfC).</li>
			<li>Based on responses to the CfC, the chair determines one of the following outcomes:
				<ul>
					<li>If no objections are received by the deadline, the draft decision becomes a formal decision of the Working Group.</li>
					<li>If objections are received but the chair believes the objections have already been considered and addressed and there is an overall consensus, the draft decision becomes a formal decision of the Working Group with objections. Objections are recorded as an appendix to the formal decision.</li>
					<li>If objections are received that the chair believes present substantive new information, or if the chair believes there is not a clear consensus in the Working Group they should reopen the discussion.</li>
					<li>If the chair determines that it is impossible to reach consensus, the chair may conduct a formal vote.</li>
				</ul>
			</li>
		</ol>
		<p>This policy includes the following guidelines and constraints for the procedures above:</p>
		<p><strong>Discussion:</strong> In order to keep the Working Group moving on its topics, the chair normally hopes to carry out discussion for two weeks, but may allow longer discussion time if necessary. Discussion may take place in any forum used by the Working Group, including mailing list, teleconference, IRC, issue tracker comments, etc. Participants should take care that at least major points are put in a place used by the plenary of the group and archived for institutional memory. During discussion on a topic, participants are welcome to raise objections liberally to make sure all viewpoints are considered. However, when the chair issues a Call for Consensus, objections should not be raised unless the individual strongly believes the decision is the wrong one in spite of discussion, and the individual cannot "live with" the decision. Compromise on points that the individual considers suboptimal but can "live with" is an essential part of group decisions that must meet various requirements.</p>
		<p><strong>Mechanism for CfC:</strong> A CfC is issued either by email to the Working Group's administrative mailing list <a href="https://lists.w3.org/Archives/Public/public-aria-admin/">public-aria-admin@w3.org</a>, or as a <a href="/2002/09/wbs/83726/">Web-based survey</a>. Emails include "Call for Consensus" or "CfC" in the subject line. Web-based surveys include those terms in the title and in the subject line of the email announcing the survey.</p>
		<p><strong>Duration of CfC:</strong> Chairs must allow <em>no fewer</em> than two business days for participants to respond, but may allow longer periods, and for non-urgent decisions as much as five business days is encouraged. The definition of "business days" excludes the weekend days Saturday and Sunday, and one- or two-day statutory holidays in jurisdictions in which active participants are based. A business day is defined as the 24-hour time period beginning when a CfC is issued, and is extended by an additional 24 hours for each weekend day or holiday. Thus a CfC issued on Friday at noon in a particular time zone would not close any earlier than the following Tuesday at noon in the same time zone (ensuring a full working day is encompassed for people in all time zones). A CfC issued on Tuesday at noon where there is a statutory holiday on Wednesday would not close any earlier than Friday at noon. If the chair overlooks a holiday when setting a deadline, participants can inform the chair and the deadline will be extended appropriately.</p>
		<p><strong>Responding to CfC:</strong> Participants respond to an email CfC by responding to the email on list, expressing support or opposition&mdash;often using the shorthand "+1" or "-1" respectively, or "+0" to record abstention. A CfC in a Web-based survey will have similar response options. A participant who does not respond to a CfC by the deadline will be presumed to have assented. Participants may include discussion in their response but should clarify whether they request the consensus to fail and discussion to be reopened, or if the discussion is a "friendly amendment" but the proposed resolution is nonetheless supported.</p>
		<p><strong>Record of decisions:</strong> The Working Group maintains a <a href="wiki/Decisions">log of formal decisions</a>. When a resolution is ratified, the chair or staff contact appends the decision to the log.</p>
		<p><strong>Resolutions in teleconferences:</strong> The Working Group uses minuted teleconferences as an important and effective means of identifying and resolving issues relatively quickly. The participants in the teleconference may come to consensus and record a resolution. Because not all WG participants are necessarily able to participate in a given teleconference, resolutions in teleconferences are not automatically formal decisions of the Working Group, until confirmed by a Call for Consensus. If resolutions are made in a teleconference, the chair may issue a Call for Consensus on each item logged as a resolution in the minutes, providing relevant URIs to minutes, affected document text, issues, and actions when available. If the chair believes wider discussion is needed, they may choose not to issue a CfC on a teleconference resolution, in which case it does not become a formal decision until the full process is completed.</p>
		<p><strong>Participant unavailability:</strong> If participants with an active interest in the outcome of the decision are on leave due to vacation, sick leave, longer holidays, etc., they may request that a CfC not be issued during their absence, or that the deadline be extended. Due to the potential impact on Working Group timelines, the chair must use reasonable judgement about whether to grant the delay or extension. The chair must not use the policy timelines to exclude an important perspective, but participants must not expect the Working Group to cease decision-making during an extended absence.</p>
		<p><strong>Appeals:</strong> If a participant believes the chair has not exercised sound judgment in following this policy, they should express their concern first to the chair, escalate if needed to the staff contact, and if still needed escalate to the W3C Web Accessibility Initiative Domain Lead.</p>
		<p><strong>Votes:</strong> It is the intent of this policy for the Working Group to make decisions by consensus in a timely manner. If, after executing these procedures, including re-opening the discussion at least once, the chair determines consensus is unachievable, the <a href="charter">Working Group charter</a> allows for a <a href="https://www.w3.org/Consortium/Process/#Votes">vote</a> which is carried out according to W3C Process. Resorting to voting is highly undesirable, and the intent of this decision policy is to avoid voting.</p>

<?php include "_footer.phi"; ?>
	</body>
</html>