# netlify.toml
# Basic configuration for a Netlify deployment
[build]
  publish = "" # Directory to publish
  command = "./pr-preview.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  NODE_ENV = "Deploy"

[context.branch-deploy.environment]
  NODE_ENV = "development"