name: Node CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate-and-publish:
    name: Validate and publish to gh-pages
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
          BUILD_FAIL_ON: nothing
          GH_PAGES_BUILD_OVERRIDE: |
            lint: false