name: core-aam
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'core-aam/**'
      - '.github/workflows/core-aam.yml'
  workflow_dispatch:

concurrency:
  group: gh-pages-push
  queue: max

jobs:
  update-core-aam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: core-aam/index.html
          DESTINATION: core-aam/index.html
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: nothing
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_CORE_AAM }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          W3C_BUILD_OVERRIDE: |
            specStatus: CRD

