name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5 # Uploads repository content to the runner
    - uses: actions/labeler@v6
      with:
        sync-labels: true
