name: aria WDD publication
on:
  push:
    branches: [aria-WD-prep]
    paths:
    - 'common/**'
    - index.html
  workflow_dispatch:
jobs:
  main:
    name: ARIA WD
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ARIA_WD_ECHIDNA_TOKEN }}
          # Replace following with appropriate value. See options.md for details.
          W3C_WG_DECISION_URL: https://www.w3.org/2026/05/28-aria-minutes.html